### ISSUE TITLE
How to help?

### ISSUE THREAD

**Issue by TroyWitthoeft** [CoVital-Project/covital-android#1]
I'm new here.  How do I get setup to contribute?  On Windows?  On Mac?  Should we use Visual Studio Code?  Any Kotlin getting started guides to recommend? If there is a place where this is covered can you link me to it?  Thank you.

**Comment by lotdrops** [comment]
Doesn't matter windows, mac or linux. You should use Android Studio.

Regarding getting started, are you familiar with android development? That would be the first step if not.

**Comment by kaeawc** [comment]
@TroyWitthoeft  You should join the [Helpful Engineering](https://helpfulengineering.org/) Slack and join CoVital's channel there (`#project-monitoring-o2`). You'll find a lot of resources for getting started with the project there. We're working on docs and organizing work.

**Comment by kaeawc** [comment]
@TroyWitthoeft I've started creating a number of issues and documentation about how to get started. If you see an issue marked with `good first issue` please comment on it and make a PR.
